"""Android brain memory starter package."""

from .models import (
    MemoryCandidate,
    SalienceFeatures,
    SalienceResult,
    Episode,
    Fact,
    MemoryQuery,
    MemoryBundle,
    MemoryStatus,
    Speakability,
    SourceType,
    parse_memory_status,
    parse_speakability,
    parse_source_type,
    validate_confidence,
    validate_salience,
    validate_timestamp,
    validate_timestamp_range,
)
from .salience import (
    PromotionThresholds,
    SalienceScoringConfig,
    load_salience_config,
    promotion_decision,
    score_candidate,
    threshold_for_score,
)
from .storage import (
    FactConflictReport,
    FactSupportRecord,
    MemoryStore,
    MemorySummaryRecord,
    MetaMemoryRecord,
    MigrationRecord,
    RawTraceRecord,
    WorkingContextSnapshot,
)
from .retrieval import retrieve_memory
from .consolidation import ConsolidationOptions, ConsolidationReport, consolidate_once
from .consolidation_daemon import ConsolidationDaemon
from .engine import FactUpsertResult, MemoryEngine, MnemeMemory, RememberCandidateResult
from .attention import AttentionManager, AttentionState, AttentionTarget
from .executive import Executive, ExecutiveGoal, ExecutiveIntent, ExecutiveIntentType, ExecutiveMode
from .runtime import (
    EventBus,
    RuntimeEvent,
    RuntimeEventKind,
    RuntimeTopic,
    Subscription,
    attention_update,
    executive_intent,
    memory_candidate_event,
    memory_lifecycle_event,
    perception_observation,
    safety_event,
    skill_goal,
    skill_status,
    world_state_update,
)
from .context_windows import ContextWindow, ContextWindowManager
from .decay import DecayOptions, DecayReport, purge_memory, run_decay_once
from .dialogue import DialogueActType, DialoguePlanner, UtterancePlan
from .extraction import FactExtractionReport, FactExtractor, statement_fact_id
from .promotion import MemoryPromoter, PromotionOutcome
from .live_perception import (
    CameraCaptureBackend,
    CapturedFrame,
    CommandFrameCaptureBackend,
    CommandSpeechRecognitionBackend,
    LivePerceptionReport,
    LiveSpeechWorker,
    LiveVisionWorker,
    NoopCameraCaptureBackend,
    NoopSpeechRecognitionBackend,
    PerceptionFusionCalibrator,
    PerceptionRetentionPolicy,
    ScriptedCameraCaptureBackend,
    ScriptedSpeechRecognitionBackend,
    SpeechRecognitionBackend,
    SpeechTranscriptObservation,
)
from .peripherals import (
    FakePeripheralBackend,
    PeripheralDevice,
    PeripheralDiscoveryService,
    PeripheralKind,
    PeripheralSnapshot,
    RealPeripheralBackend,
    default_host_peripheral_backend,
)
from .runtime_loop import (
    MnemeRuntime,
    RuntimeClock,
    RuntimeStepResult,
    VirtualHeadOutput,
    candidate_from_user_utterance,
)
from .self_model import ProceduralMemory, SelfModel
from .working_memory import EchoFragment, SensoryEchoBuffer, WorkingMemory, WorkingMemorySnapshot
from .world_model import (
    InternalState,
    PersonPresence,
    SoundState,
    SpeechActivity,
    TouchState,
    WorldModel,
    WorldModelSnapshot,
)
from .simulation import (
    BodyHealthWorker,
    FacePersonWorker,
    ReplayResult,
    Scenario,
    ScenarioReplayRunner,
    ScenarioStep,
    SoundDirectionWorker,
    SpeechTranscriptWorker,
    TouchWorker,
    load_scenario,
)

__all__ = [
    "MemoryCandidate",
    "SalienceFeatures",
    "SalienceResult",
    "Episode",
    "Fact",
    "MemoryQuery",
    "MemoryBundle",
    "MemoryStatus",
    "Speakability",
    "SourceType",
    "parse_memory_status",
    "parse_speakability",
    "parse_source_type",
    "validate_confidence",
    "validate_salience",
    "validate_timestamp",
    "validate_timestamp_range",
    "PromotionThresholds",
    "SalienceScoringConfig",
    "load_salience_config",
    "score_candidate",
    "promotion_decision",
    "threshold_for_score",
    "MemoryStore",
    "FactConflictReport",
    "FactSupportRecord",
    "MemorySummaryRecord",
    "RawTraceRecord",
    "MetaMemoryRecord",
    "MigrationRecord",
    "WorkingContextSnapshot",
    "retrieve_memory",
    "ConsolidationOptions",
    "ConsolidationReport",
    "ConsolidationDaemon",
    "consolidate_once",
    "MnemeMemory",
    "MemoryEngine",
    "RememberCandidateResult",
    "FactUpsertResult",
    "AttentionManager",
    "AttentionState",
    "AttentionTarget",
    "Executive",
    "ExecutiveGoal",
    "ExecutiveIntent",
    "ExecutiveIntentType",
    "ExecutiveMode",
    "EventBus",
    "RuntimeEvent",
    "RuntimeEventKind",
    "RuntimeTopic",
    "Subscription",
    "perception_observation",
    "world_state_update",
    "attention_update",
    "memory_candidate_event",
    "memory_lifecycle_event",
    "MemoryPromoter",
    "PromotionOutcome",
    "CameraCaptureBackend",
    "CapturedFrame",
    "CommandFrameCaptureBackend",
    "CommandSpeechRecognitionBackend",
    "LivePerceptionReport",
    "LiveSpeechWorker",
    "LiveVisionWorker",
    "NoopCameraCaptureBackend",
    "NoopSpeechRecognitionBackend",
    "PerceptionFusionCalibrator",
    "PerceptionRetentionPolicy",
    "ScriptedCameraCaptureBackend",
    "ScriptedSpeechRecognitionBackend",
    "SpeechRecognitionBackend",
    "SpeechTranscriptObservation",
    "PeripheralKind",
    "PeripheralDevice",
    "PeripheralSnapshot",
    "FakePeripheralBackend",
    "RealPeripheralBackend",
    "PeripheralDiscoveryService",
    "default_host_peripheral_backend",
    "MnemeRuntime",
    "RuntimeClock",
    "RuntimeStepResult",
    "VirtualHeadOutput",
    "candidate_from_user_utterance",
    "FactExtractor",
    "FactExtractionReport",
    "statement_fact_id",
    "DecayOptions",
    "DecayReport",
    "run_decay_once",
    "purge_memory",
    "WorldModel",
    "WorldModelSnapshot",
    "ContextWindow",
    "ContextWindowManager",
    "DialogueActType",
    "DialoguePlanner",
    "UtterancePlan",
    "SelfModel",
    "ProceduralMemory",
    "PersonPresence",
    "SpeechActivity",
    "SoundState",
    "TouchState",
    "InternalState",
    "executive_intent",
    "skill_goal",
    "skill_status",
    "safety_event",
    "EchoFragment",
    "SensoryEchoBuffer",
    "WorkingMemory",
    "WorkingMemorySnapshot",
    "Scenario",
    "ScenarioStep",
    "ReplayResult",
    "ScenarioReplayRunner",
    "load_scenario",
    "FacePersonWorker",
    "SpeechTranscriptWorker",
    "SoundDirectionWorker",
    "TouchWorker",
    "BodyHealthWorker",
]
